/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_ajout (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_Recherche (void);
GtkWidget* create_Modification (void);
GtkWidget* create_affiche (void);
GtkWidget* create_enregistrement (void);
GtkWidget* create_dashboard (void);
GtkWidget* create_attention_rech (void);
GtkWidget* create_gb_welcome (void);
GtkWidget* create_gb_aff (void);
GtkWidget* create_gb_add (void);
GtkWidget* create_gb_modifier (void);
GtkWidget* create_gb_liste (void);
GtkWidget* create_windowajouter_reclamation (void);
GtkWidget* create_windowafficher_reclamation (void);
GtkWidget* create_windowserviceleplusreclame (void);
GtkWidget* create_gestionyes (void);
GtkWidget* create_ajyes (void);
GtkWidget* create_myes (void);
GtkWidget* create_suppyes (void);
GtkWidget* create_cheryes (void);
GtkWidget* create_bestyes (void);
GtkWidget* create_windowGestionCapteurs (void);
GtkWidget* create_windowAjoutCapteur (void);
GtkWidget* create_windowModifierCapteur (void);
GtkWidget* create_windowSupprimeCapteur (void);
GtkWidget* create_windowListeCapteurs (void);
GtkWidget* create_ModifierCapteur (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_windowRemplir (void);
GtkWidget* create_window1 (void);
GtkWidget* create_Acceuila (void);
GtkWidget* create_Ajoutera (void);
GtkWidget* create_Suppresiona (void);
GtkWidget* create_cherchera (void);
GtkWidget* create_Affichera (void);
GtkWidget* create_Dashboarda (void);
GtkWidget* create_window1a (void);
