/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *acceuil;
  GtkWidget *ajout;
  GtkWidget *supprimer;
  GtkWidget *Recherche;
  GtkWidget *Modification;
  GtkWidget *affiche;
  GtkWidget *enregistrement;
  GtkWidget *dashboard;
  GtkWidget *attention_rech;
  GtkWidget *gb_welcome;
  GtkWidget *gb_aff;
  GtkWidget *gb_add;
  GtkWidget *gb_modifier;
  GtkWidget *gb_liste;
  GtkWidget *windowajouter_reclamation;
  GtkWidget *windowafficher_reclamation;
  GtkWidget *windowserviceleplusreclame;
  GtkWidget *gestionyes;
  GtkWidget *ajyes;
  GtkWidget *myes;
  GtkWidget *suppyes;
  GtkWidget *cheryes;
  GtkWidget *bestyes;
  GtkWidget *windowGestionCapteurs;
  GtkWidget *windowAjoutCapteur;
  GtkWidget *windowModifierCapteur;
  GtkWidget *windowSupprimeCapteur;
  GtkWidget *windowListeCapteurs;
  GtkWidget *ModifierCapteur;
  GtkWidget *dialog1;
  GtkWidget *dialog2;
  GtkWidget *dialog3;
  GtkWidget *windowRemplir;
  GtkWidget *window1;
  GtkWidget *Acceuila;
  GtkWidget *Ajoutera;
  GtkWidget *Suppresiona;
  GtkWidget *cherchera;
  GtkWidget *Affichera;
  GtkWidget *Dashboarda;
  GtkWidget *window1a;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*acceuil = create_acceuil ();
  gtk_widget_show (acceuil);
  ajout = create_ajout ();
  gtk_widget_show (ajout);
  supprimer = create_supprimer ();
  gtk_widget_show (supprimer);
  Recherche = create_Recherche ();
  gtk_widget_show (Recherche);
  Modification = create_Modification ();
  gtk_widget_show (Modification);
  affiche = create_affiche ();
  gtk_widget_show (affiche);
  enregistrement = create_enregistrement ();
  gtk_widget_show (enregistrement);
  dashboard = create_dashboard ();
  gtk_widget_show (dashboard);
  attention_rech = create_attention_rech ();
  gtk_widget_show (attention_rech);*/
  gb_welcome = create_gb_welcome ();
  gtk_widget_show (gb_welcome);
  /*gb_aff = create_gb_aff ();
  gtk_widget_show (gb_aff);
  gb_add = create_gb_add ();
  gtk_widget_show (gb_add);
  gb_modifier = create_gb_modifier ();
  gtk_widget_show (gb_modifier);
  gb_liste = create_gb_liste ();
  gtk_widget_show (gb_liste);
  windowajouter_reclamation = create_windowajouter_reclamation ();
  gtk_widget_show (windowajouter_reclamation);
  windowafficher_reclamation = create_windowafficher_reclamation ();
  gtk_widget_show (windowafficher_reclamation);
  windowserviceleplusreclame = create_windowserviceleplusreclame ();
  gtk_widget_show (windowserviceleplusreclame);
  gestionyes = create_gestionyes ();
  gtk_widget_show (gestionyes);
  ajyes = create_ajyes ();
  gtk_widget_show (ajyes);
  myes = create_myes ();
  gtk_widget_show (myes);
  suppyes = create_suppyes ();
  gtk_widget_show (suppyes);
  cheryes = create_cheryes ();
  gtk_widget_show (cheryes);
  bestyes = create_bestyes ();
  gtk_widget_show (bestyes);
  windowGestionCapteurs = create_windowGestionCapteurs ();
  gtk_widget_show (windowGestionCapteurs);
  windowAjoutCapteur = create_windowAjoutCapteur ();
  gtk_widget_show (windowAjoutCapteur);
  windowModifierCapteur = create_windowModifierCapteur ();
  gtk_widget_show (windowModifierCapteur);
  windowSupprimeCapteur = create_windowSupprimeCapteur ();
  gtk_widget_show (windowSupprimeCapteur);
  windowListeCapteurs = create_windowListeCapteurs ();
  gtk_widget_show (windowListeCapteurs);
  ModifierCapteur = create_ModifierCapteur ();
  gtk_widget_show (ModifierCapteur);
  dialog1 = create_dialog1 ();
  gtk_widget_show (dialog1);
  dialog2 = create_dialog2 ();
  gtk_widget_show (dialog2);
  dialog3 = create_dialog3 ();
  gtk_widget_show (dialog3);
  windowRemplir = create_windowRemplir ();
  gtk_widget_show (windowRemplir);
  window1 = create_window1 ();
  gtk_widget_show (window1);
  Acceuila = create_Acceuila ();
  gtk_widget_show (Acceuila);
  Ajoutera = create_Ajoutera ();
  gtk_widget_show (Ajoutera);
  Suppresiona = create_Suppresiona ();
  gtk_widget_show (Suppresiona);
  cherchera = create_cherchera ();
  gtk_widget_show (cherchera);
  Affichera = create_Affichera ();
  gtk_widget_show (Affichera);
  Dashboarda = create_Dashboarda ();
  gtk_widget_show (Dashboarda);
  window1a = create_window1a ();
  gtk_widget_show (window1a);*/

  gtk_main ();
  return 0;
}

